# -*- coding: utf-8 -*-
"""LLM Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmmwAbCE8q0dirbLCDglyxRpK4pSvhkW
"""

from transformers import pipeline

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

text = input("Enter your paragraph:\n")

output = summarizer(text, max_length=100, min_length=30, do_sample=False)

print("\n🔍 Summary:\n")
print(output[0]['summary_text'])